# Usa una imagen base de Node.js con Alpine Linux
FROM node:alpine AS builder


# Definir variables de entorno
ENV API="http://131.107.5.106:3000"

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY . .

# Instala las dependencias y construye la aplicación Angular
RUN npm install && npm run build

# Segunda etapa para una imagen más pequeña
FROM nginx:alpine

# Copia el archivo de configuracion al contenedor
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia los archivos construidos desde la etapa anterior
COPY --from=builder /app/dist/frontend /usr/share/nginx/html

# Expone el puerto 80 para la aplicación Angular
EXPOSE 80

# Comando predeterminado para iniciar Nginx y servir la aplicación
CMD ["nginx", "-g", "daemon off;"]