version: '3'

services:
  frontend:
    image: rocket1530/frontend
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - msdatos

  msdatos:
    image: rocket1530/ms-datos
    ports:
      - "3001:3001"
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
