version: '3.9'

services:
  frontend-dockflow:
    image: rocket1530/frontend-dockflow:latest
    container_name: frontend-dockflow
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/selfsigned.crt:/etc/ssl/certs/registromercantil_gob_gt.crt:ro
      - ./certs/selfsigned.key:/etc/ssl/registromercantil_gob_gt.key:ro
    depends_on:
      - frontend-dockflow
