FROM alpine

ENV SERVER_PORT="3002"
ENV API="https://apirep.registromercantil.gob.gt"

RUN apk add --update nodejs npm
WORKDIR /app

COPY package.json /app
RUN npm install
COPY . .

# Cambiar por el puerto que vaya a utilizar la aplicación
EXPOSE 3002

CMD ["node", "index.js"]