FROM alpine

ENV SERVER_PORT="3001"
ENV API="https://apirep.registromercantil.gob.gt"
ENV DATABASE_ADDR="131.107.5.106"
ENV KEYSPACE="sistema_nuevo"

RUN apk add --update nodejs npm
WORKDIR /app

COPY package.json /app
RUN npm install
COPY . .

# Cambiar por el puerto que vaya a utilizar la aplicación
EXPOSE 3001

CMD ["node", "index.js"]